# 학습이 잘 되는 모델


*   사용할 레이어
  *   tf.keras.layers.BatchNormalization()
  *   tf.keras.layers.Activation('swish')

*   데이터
  *   보스턴 집 값 예측: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv
  *   붓 꽃 품종 분류: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv


### 라이브러리 불러오기

In [ ]:
import tensorflow as tf
import pandas as pd

## 보스턴 집 값 예측

### 과거의 데이터를 준비

In [ ]:
boston_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
boston = pd.read_csv(boston_path)

In [ ]:
boston.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')

### 독립 변수와 종속 변수 설정

In [ ]:
boston_inde = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
boston_de = boston[['medv']]

In [ ]:
print(boston_inde.shape, boston_de.shape)

(506, 13) (506, 1)


### 모델 생성

In [ ]:
X = tf.keras.layers.Input(shape=[13])
H1 = tf.keras.layers.Dense(8, activation='swish')(X)
H2 = tf.keras.layers.Dense(8, activation='swish')(H1)
H3 = tf.keras.layers.Dense(8, activation='swish')(H2)
Y = tf.keras.layers.Dense(1)(H3)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

#### 더 좋은 결과를 얻기 위하여 BatchNormalization() 사용

In [ ]:
X = tf.keras.layers.Input(shape=[13])

H1 = tf.keras.layers.Dense(8)(X)
H1 = tf.keras.layers.BatchNormalization()(H1)
H1 = tf.keras.layers.Activation('swish')(H1)

H2 = tf.keras.layers.Dense(8)(H1)
H2 = tf.keras.layers.BatchNormalization()(H2)
H2 = tf.keras.layers.Activation('swish')(H2)

H3 = tf.keras.layers.Dense(8)(H2)
H3 = tf.keras.layers.BatchNormalization()(H3)
H3 = tf.keras.layers.Activation('swish')(H3)

Y = tf.keras.layers.Dense(1)(H3)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

### 모델 학습

In [ ]:
model.fit(boston_inde, boston_de, epochs=1000, verbose=2)

Epoch 1/1000
16/16 - 1s - loss: 585.4238
Epoch 2/1000
16/16 - 0s - loss: 576.8678
Epoch 3/1000
16/16 - 0s - loss: 569.8766
Epoch 4/1000
16/16 - 0s - loss: 563.2479
Epoch 5/1000
16/16 - 0s - loss: 557.2811
Epoch 6/1000
16/16 - 0s - loss: 551.9385
Epoch 7/1000
16/16 - 0s - loss: 546.9617
Epoch 8/1000
16/16 - 0s - loss: 541.2273
Epoch 9/1000
16/16 - 0s - loss: 535.9772
Epoch 10/1000
16/16 - 0s - loss: 530.4412
Epoch 11/1000
16/16 - 0s - loss: 525.1707
Epoch 12/1000
16/16 - 0s - loss: 519.6337
Epoch 13/1000
16/16 - 0s - loss: 514.4514
Epoch 14/1000
16/16 - 0s - loss: 509.5304
Epoch 15/1000
16/16 - 0s - loss: 503.2759
Epoch 16/1000
16/16 - 0s - loss: 497.0475
Epoch 17/1000
16/16 - 0s - loss: 491.5474
Epoch 18/1000
16/16 - 0s - loss: 485.6644
Epoch 19/1000
16/16 - 0s - loss: 479.2015
Epoch 20/1000
16/16 - 0s - loss: 473.3344
Epoch 21/1000
16/16 - 0s - loss: 467.2965
Epoch 22/1000
16/16 - 0s - loss: 462.5343
Epoch 23/1000
16/16 - 0s - loss: 454.6145
Epoch 24/1000
16/16 - 0s - loss: 447.8426
E

### 모델 확인

In [ ]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 8)                 112       
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9         
Total params: 265
Trainable params: 265
Non-trainable params: 0
_________________________________________________________________


### 모델 이용

In [ ]:
print(model.predict(boston_inde[:10]))
print(boston_de[:10])

[[31.857182]
 [24.450125]
 [32.809715]
 [32.2775  ]
 [30.977306]
 [27.153225]
 [23.907446]
 [18.348692]
 [14.880705]
 [18.530628]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2
5  28.7
6  22.9
7  27.1
8  16.5
9  18.9


## 붓 꽃 품종 분류

### 과거의 데이터 준비

In [ ]:
iris_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(iris_path)

In [ ]:
iris.columns

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')

In [ ]:
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

### 독립 변수와 종속 변수 설정

In [ ]:
iris_inde = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
iris_de = iris[['품종']]

In [ ]:
iris_de = pd.get_dummies(iris_de)

In [ ]:
print(iris_inde.shape, iris_de.shape)

(150, 4) (150, 3)


### 모델 생성

In [ ]:
X = tf.keras.layers.Input(shape=[4])
H1 = tf.keras.layers.Dense(8, activation='swish')(X)
H2 = tf.keras.layers.Dense(8, activation='swish')(H1)
H3 = tf.keras.layers.Dense(8, activation='swish')(H2)
Y = tf.keras.layers.Dense(3, activation='softmax')(H3)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

#### 더 좋은 결과를 얻기 위하여 BatchNormalization() 사용

In [ ]:
X = tf.keras.layers.Input(shape=[4])

H1 = tf.keras.layers.Dense(8)(X)
H1 = tf.keras.layers.BatchNormalization()(H1)
H1 = tf.keras.layers.Activation('swish')(H1)

H2 = tf.keras.layers.Dense(8)(H1)
H2 = tf.keras.layers.BatchNormalization()(H2)
H2 = tf.keras.layers.Activation('swish')(H2)

H3 = tf.keras.layers.Dense(8)(H2)
H3 = tf.keras.layers.BatchNormalization()(H3)
H3 = tf.keras.layers.Activation('swish')(H3)

Y = tf.keras.layers.Dense(3, activation='softmax')(H3)

model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

### 모델 학습

In [ ]:
model.fit(iris_inde, iris_de, epochs=300)

Epoch 1/300
5/5 [==============================] - 1s 4ms/step - loss: 1.0839 - accuracy: 0.4400
Epoch 2/300
5/5 [==============================] - 0s 5ms/step - loss: 0.8954 - accuracy: 0.7600
Epoch 3/300
5/5 [==============================] - 0s 4ms/step - loss: 0.8268 - accuracy: 0.8400
Epoch 4/300
5/5 [==============================] - 0s 3ms/step - loss: 0.7751 - accuracy: 0.8733
Epoch 5/300
5/5 [==============================] - 0s 4ms/step - loss: 0.7468 - accuracy: 0.8133
Epoch 6/300
5/5 [==============================] - 0s 4ms/step - loss: 0.6818 - accuracy: 0.8667
Epoch 7/300
5/5 [==============================] - 0s 4ms/step - loss: 0.6674 - accuracy: 0.8267
Epoch 8/300
5/5 [==============================] - 0s 3ms/step - loss: 0.6216 - accuracy: 0.8867
Epoch 9/300
5/5 [==============================] - 0s 4ms/step - loss: 0.6119 - accuracy: 0.8467
Epoch 10/300
5/5 [==============================] - 0s 5ms/step - loss: 0.5612 - accuracy: 0.8867
Epoch 11/300
5/5 [===========

### 모델 확인

In [ ]:
print(model.summary())

Model: "model_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_11 (InputLayer)        [(None, 4)]               0         
_________________________________________________________________
dense_35 (Dense)             (None, 8)                 40        
_________________________________________________________________
batch_normalization_22 (Batc (None, 8)                 32        
_________________________________________________________________
activation_21 (Activation)   (None, 8)                 0         
_________________________________________________________________
dense_36 (Dense)             (None, 8)                 72        
_________________________________________________________________
batch_normalization_23 (Batc (None, 8)                 32        
_________________________________________________________________
activation_22 (Activation)   (None, 8)                 0   

### 모델 이용

In [ ]:
print(model.predict(iris_inde[:10]))
print(iris_de[:10])

[[9.9997056e-01 1.4295932e-05 1.5112248e-05]
 [9.9980825e-01 1.1889638e-04 7.2876595e-05]
 [9.9991560e-01 4.9541344e-05 3.4797071e-05]
 [9.9982029e-01 1.2667147e-04 5.3056014e-05]
 [9.9997902e-01 1.0489803e-05 1.0516035e-05]
 [9.9997234e-01 1.6154563e-05 1.1458065e-05]
 [9.9990809e-01 5.9556187e-05 3.2295051e-05]
 [9.9994993e-01 2.9047987e-05 2.0973685e-05]
 [9.9965525e-01 2.5287262e-04 9.1843111e-05]
 [9.9990070e-01 6.1058847e-05 3.8258837e-05]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
5          1              0             0
6          1              0             0
7          1              0             0
8          1              0             0
9          1              0             0
