# 히든 레이어

  *   보스턴 집 값 예측: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv
  *   아이리스 품종 분류: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv

In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

# 보스턴 집 값 에측

## 데이터 불러오기

In [20]:
boston_path='https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
boston=pd.read_csv(boston_path)

In [3]:
print(boston.shape)
boston.head()

(506, 14)


crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [4]:
boston.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')

## 독립 변수와 종속 변수 지정

In [5]:
boston_inde = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
boston_de = boston[['medv']]

In [6]:
print(boston_inde.shape, boston_de.shape)

(506, 13) (506, 1)


## 모델 만들기

In [7]:
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

## 모델 학습

In [8]:
model.fit(boston_inde, boston_de, epochs=1000, verbose=2)

Epoch 1/1000
16/16 - 1s - loss: 5524.9829
Epoch 2/1000
16/16 - 0s - loss: 2832.1528
Epoch 3/1000
16/16 - 0s - loss: 1795.0273
Epoch 4/1000
16/16 - 0s - loss: 1237.2517
Epoch 5/1000
16/16 - 0s - loss: 814.2186
Epoch 6/1000
16/16 - 0s - loss: 508.9582
Epoch 7/1000
16/16 - 0s - loss: 357.0538
Epoch 8/1000
16/16 - 0s - loss: 271.2407
Epoch 9/1000
16/16 - 0s - loss: 209.3153
Epoch 10/1000
16/16 - 0s - loss: 162.7865
Epoch 11/1000
16/16 - 0s - loss: 125.2489
Epoch 12/1000
16/16 - 0s - loss: 100.8888
Epoch 13/1000
16/16 - 0s - loss: 81.3107
Epoch 14/1000
16/16 - 0s - loss: 71.8661
Epoch 15/1000
16/16 - 0s - loss: 69.2575
Epoch 16/1000
16/16 - 0s - loss: 63.3662
Epoch 17/1000
16/16 - 0s - loss: 61.7061
Epoch 18/1000
16/16 - 0s - loss: 60.1617
Epoch 19/1000
16/16 - 0s - loss: 60.1406
Epoch 20/1000
16/16 - 0s - loss: 58.3905
Epoch 21/1000
16/16 - 0s - loss: 56.8607
Epoch 22/1000
16/16 - 0s - loss: 55.9109
Epoch 23/1000
16/16 - 0s - loss: 56.4523
Epoch 24/1000
16/16 - 0s - loss: 53.9296
Epoch 25/

## 모델 확인

In [9]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


## 모델 이용



In [10]:
print(model.predict(boston_inde[:10]))
print(boston_de[:10])

[[29.725819]
 [27.15704 ]
 [29.89896 ]
 [30.946915]
 [31.030964]
 [29.279274]
 [23.712486]
 [19.135544]
 [11.136102]
 [18.949738]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2
5  28.7
6  22.9
7  27.1
8  16.5
9  18.9


# 붓 꽃 분류하기

## 데이터 불러오기


In [46]:
iris_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(iris_path)

In [47]:
iris.columns

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')

## 독립 변수와 종속 변수 지정

In [48]:
iris_inde = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
iris_de = iris[['품종']]
# 원핫 인코딩
iris_de = pd.get_dummies(iris_de)

In [49]:
print(iris_inde.shape, iris_de.shape)

(150, 4) (150, 3)


In [50]:
print(iris_inde.head())
print(iris_de.head())

   꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭
0   5.1  3.5    1.4   0.2
1   4.9  3.0    1.4   0.2
2   4.7  3.2    1.3   0.2
3   4.6  3.1    1.5   0.2
4   5.0  3.6    1.4   0.2
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


## 모델 만들기


In [51]:
X = tf.keras.layers.Input(shape=[4])
H1 = tf.keras.layers.Dense(8, activation='swish')(X)
H2 = tf.keras.layers.Dense(8, activation='swish')(H1)
H3 = tf.keras.layers.Dense(8, activation='swish')(H2)
Y = tf.keras.layers.Dense(3, activation='softmax')(H3)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

## 모델 학습

In [54]:
model.fit(iris_inde, iris_de, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 3ms/step - loss: 0.6742 - accuracy: 0.5333
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 0.6553 - accuracy: 0.4667
Epoch 3/100
5/5 [==============================] - 0s 3ms/step - loss: 0.6371 - accuracy: 0.5333
Epoch 4/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6207 - accuracy: 0.5267
Epoch 5/100
5/5 [==============================] - 0s 3ms/step - loss: 0.6040 - accuracy: 0.5533
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5898 - accuracy: 0.5733
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5749 - accuracy: 0.5933
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5619 - accuracy: 0.6667
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5496 - accuracy: 0.6800
Epoch 10/100
5/5 [==============================] - 0s 3ms/step - loss: 0.5386 - accuracy: 0.7400
Epoch 11/100
5/5 [===========

## 모델 확인


In [57]:
print(model.summary())

Model: "model_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_7 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_10 (Dense)             (None, 8)                 40        
_________________________________________________________________
dense_11 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_12 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_13 (Dense)             (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________
None


## 모델 이용

In [55]:
print(model.predict(iris_inde[:10]))
print(iris_de[:10])

[[9.9996150e-01 1.7959659e-10 3.8526843e-05]
 [9.9991763e-01 1.3949145e-09 8.2407532e-05]
 [9.9991894e-01 1.1280014e-09 8.1044884e-05]
 [9.9980730e-01 1.2788824e-08 1.9271311e-04]
 [9.9995482e-01 2.6679164e-10 4.5132481e-05]
 [9.9994075e-01 9.0149088e-10 5.9217975e-05]
 [9.9985075e-01 6.6868142e-09 1.4927283e-04]
 [9.9993324e-01 8.2956469e-10 6.6765911e-05]
 [9.9974769e-01 2.3412708e-08 2.5226129e-04]
 [9.9991810e-01 1.2980258e-09 8.1892998e-05]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
5          1              0             0
6          1              0             0
7          1              0             0
8          1              0             0
9          1              0             0
